/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f8f9fa',
        'inverse-primary': '#5edda0',
        'on-secondary-fixed-variant': '#534434',
        'on-primary-container': '#004128',
        error: '#ba1a1a',
        'on-surface': '#191c1d',
        'on-secondary-fixed': '#25190c',
        'secondary-fixed': '#f5dfc8',
        'surface-dim': '#d9dadb',
        'on-background': '#191c1d',
        'surface-container-highest': '#e1e3e4',
        'on-tertiary-fixed-variant': '#83242e',
        primary: '#006c46',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#005234',
        tertiary: '#a23b43',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#6d1320',
        'tertiary-fixed': '#ffdad9',
        'on-error-container': '#93000a',
        'on-surface-variant': '#3d4a41',
        'outline-variant': '#bccabf',
        'primary-container': '#2eb67d',
        'primary-fixed-dim': '#5edda0',
        'secondary-container': '#f5dfc8',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#ffb3b4',
        'tertiary-container': '#f67b81',
        'surface-container-low': '#f3f4f5',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'inverse-on-surface': '#f0f1f2',
        outline: '#6d7a71',
        'on-secondary-container': '#726250',
        'surface-bright': '#f8f9fa',
        secondary: '#6c5c4a',
        surface: '#f8f9fa',
        'inverse-surface': '#2e3132',
        'primary-fixed': '#7cfabb',
        'on-primary-fixed': '#002112',
        'surface-variant': '#e1e3e4',
        'on-tertiary-fixed': '#40000a',
        'secondary-fixed-dim': '#d8c3ad',
        'surface-tint': '#006c46',
        'surface-container': '#edeeef',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        xs: '4px',
        base: '4px',
        sm: '8px',
        gutter: '16px',
        'margin-desktop': '40px',
        '2xl': '48px',
        xl: '32px',
        'margin-mobile': '20px',
        lg: '24px',
        md: '16px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        caption: ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
